#! /usr/bin/env bash

# Shows the output of every command
set +x

activate_hm() {
  BAKFILE=~/.config/orage/oragerc.bak
  if [ -f "$BAKFILE" ]; then
    rm $BAKFILE
  fi

  HOME_MANAGER_BACKUP_EXT=bak result/activate
}

switch_display() {
  autorandr --change
  systemctl --user restart polybar.service
}

rebuild_hyprland_edp() {
  nix build .#homeConfigurations.hyprland-edp.activationPackage
  activate_hm
}

rebuild_hyprland_hdmi() {
  nix build .#homeConfigurations.hyprland-hdmi.activationPackage
  activate_hm
}

rebuild_hyprland_hdmi_mutable() {
  nix build .#homeConfigurations.hyprland-hdmi-mutable.activationPackage
  activate_hm
}

rebuild_mac_2015() {
  sudo nixos-rebuild switch --flake .#mac-2015
}

rebuild_mac_2015_vm() {
  nixos-rebuild build-vm --flake .#mac-2015
}

restart_X() {
  echo "⚠️ Restarting X11 (requires authentication) ⚠️"
  systemctl restart display-manager
}

# for fresh install only
pre_home() {
  echo "Creating config / cache directories..."

  # Polybar logs
  mkdir -p $HOME/.config/polybar/logs
  touch $HOME/.config/polybar/logs/bottom.log
  touch $HOME/.config/polybar/logs/top.log

  # FZF cache
  mkdir -p $HOME/.cache/fzf-hoogle
  touch $HOME/.cache/fzf-hoogle/cache.json

  # Desktop pic
  mkdir -p $HOME/Pictures/
  cp imgs/nixos.png $HOME/Pictures/

  # Nix daemon config for normal user
  mkdir -p $HOME/.config/nix
  cp home/daemon.conf $HOME/.config/nix/nix.conf
}

post_home() {
  # Set user's profile picture for Gnome3
  # Set screenlock wallpaper
  echo "Setting screen-lock wallpaper"
  multilockscreen -u imgs/nixos.png
}
# end of fresh install section

case $1 in
  "hpedp")
    rebuild_hyprland_edp;;
  "hphdmi")
    rebuild_hyprland_hdmi;;
  "hphdmi-mutable")
    rebuild_hyprland_hdmi_mutable;;
  "display")
    switch_display;;
  "restart-x")
    restart_X;;
  "update-fish")
    fish -c fish_update_completions;;
  "mac")
    rebuild_mac_2015;;
  "vm")
    rebuild_mac_2015_vm;;
  *)
    echo "Wrong argument: look at the switch script.";;
esac
